name: rails_event_store
on:
  push:
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
  pull_request:
    types: [opened, reopened]
    paths-ignore:
      - "railseventstore.org/**"
      - "contrib/**"
jobs:
  test:
    runs-on: [self-hosted, ubuntu-20.04]
    env:
      WORKING_DIRECTORY: rails_event_store
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
          - ruby: ruby-2.7
            gemfile: Gemfile.rails_6_0
          - ruby: ruby-2.6
            gemfile: Gemfile.rails_5_2
          - ruby: ruby-2.6
            gemfile: Gemfile.rails_6_0
          - ruby: ruby-2.7
            gemfile: Gemfile
          - ruby: ruby-2.6
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}

  mutate:
    runs-on: [self-hosted, ubuntu-20.04]
    env:
      WORKING_DIRECTORY: rails_event_store
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby: ruby-3.0
            gemfile: Gemfile
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: test -e ${{ matrix.gemfile }}.lock
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate-changes
        working-directory: ${{ env.WORKING_DIRECTORY }}
